from django.contrib import admin
from .models import *

admin.site.register(Brother)
admin.site.register(ChapterEvent)
admin.site.register(Excuse)
admin.site.register(ServiceEvent)
admin.site.register(PhilanthropyEvent)
admin.site.register(RecruitmentEvent)
admin.site.register(StudyTableEvent)
admin.site.register(ServiceSubmission)
admin.site.register(Semester)
admin.site.register(ScholarshipReport)
admin.site.register(Position)
admin.site.register(PotentialNewMember)
admin.site.register(CommitteeMeetingEvent)
admin.site.register(Committee)
admin.site.register(Supplies)
admin.site.register(Photo)
admin.site.register(MinecraftPhoto)
admin.site.register(MediaAccount)
admin.site.register(OnlineMedia)
admin.site.register(Classes)
admin.site.register(Grade)
admin.site.register(MeetABrother)
admin.site.register(Report)
