# Generated by Django 3.0.7 on 2020-09-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('2', 'Scholarship'), ('3', 'Unassigned'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('0', 'Recruitment'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('4', 'Unassigned'), ('3', 'Social')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('6', 'Scholarship'), ('0', 'Recruitment'), ('4', 'Alumni Relations'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('5', 'Membership Development'), ('3', 'Social')], max_length=1),
        ),
    ]
