# Generated by Django 3.0.7 on 2021-01-02 21:30

import dashboard.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterevent',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='event',
            name='eligible_attendees',
            field=models.ManyToManyField(blank=True, default=dashboard.models.all_actives_and_candidates, related_name='_event_eligible_attendees_+', to='dashboard.Brother'),
        ),
        migrations.AddField(
            model_name='event',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='meeting_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.'), (datetime.time(21, 0), '9:00 P.M.'), (datetime.time(21, 30), '9:30 P.M.'), (datetime.time(22, 0), '10:00 P.M.'), (datetime.time(22, 30), '10:30 P.M.'), (datetime.time(23, 0), '11:00 P.M.'), (datetime.time(23, 30), '11:30 P.M.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.'), (datetime.time(21, 0), '9:00 P.M.'), (datetime.time(21, 30), '9:30 P.M.'), (datetime.time(22, 0), '10:00 P.M.'), (datetime.time(22, 30), '10:30 P.M.'), (datetime.time(23, 0), '11:00 P.M.'), (datetime.time(23, 30), '11:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.'), (datetime.time(21, 0), '9:00 P.M.'), (datetime.time(21, 30), '9:30 P.M.'), (datetime.time(22, 0), '10:00 P.M.'), (datetime.time(22, 30), '10:30 P.M.'), (datetime.time(23, 0), '11:00 P.M.'), (datetime.time(23, 30), '11:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Event'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2021),
        ),
    ]
