# Generated by Django 3.1 on 2020-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('0', 'Alumni Relations'), ('3', 'Unassigned'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('3', 'Social'), ('0', 'Recruitment'), ('2', 'Health and Safety'), ('4', 'Unassigned'), ('1', 'Public Relations')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('3', 'Social'), ('0', 'Recruitment'), ('5', 'Membership Development'), ('6', 'Scholarship'), ('2', 'Health and Safety'), ('4', 'Alumni Relations'), ('1', 'Public Relations')], max_length=1),
        ),
    ]
