# Generated by Django 3.0.7 on 2020-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('1', 'Membership Development'), ('0', 'Alumni Relations'), ('3', 'Unassigned')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('4', 'Unassigned'), ('3', 'Social'), ('1', 'Public Relations'), ('2', 'Health and Safety'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('4', 'Alumni Relations'), ('3', 'Social'), ('1', 'Public Relations'), ('6', 'Scholarship'), ('2', 'Health and Safety'), ('0', 'Recruitment'), ('5', 'Membership Development')], max_length=1),
        ),
    ]
