# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='brother_status',
            field=models.CharField(choices=[(b'0', b'Candidate'), (b'1', b'Brother'), (b'2', b'Alumni')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='brother',
            name='current_residence',
            field=models.CharField(default=b'Theta Chi House', max_length=200),
        ),
        migrations.AddField(
            model_name='brother',
            name='hometown',
            field=models.CharField(default=b'Cleveland, OH', max_length=200),
        ),
        migrations.AddField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(default=b'Not assigned', max_length=200),
        ),
        migrations.AddField(
            model_name='brother',
            name='room_number',
            field=models.CharField(default=b'NA', max_length=3),
        ),
        migrations.AddField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(default=b'Not assigned', max_length=200),
        ),
        migrations.AlterField(
            model_name='brother',
            name='case_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brother',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brother',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
