# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160619_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brother',
            old_name='case_id',
            new_name='case_ID',
        ),
    ]
