# Generated by Django 3.0.7 on 2020-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200823_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('3', 'Unassigned'), ('1', 'Membership Development'), ('0', 'Alumni Relations')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('4', 'Unassigned'), ('1', 'Public Relations'), ('3', 'Social'), ('0', 'Recruitment'), ('2', 'Health and Safety')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('5', 'Membership Development'), ('1', 'Public Relations'), ('3', 'Social'), ('0', 'Recruitment'), ('6', 'Scholarship'), ('2', 'Health and Safety'), ('4', 'Alumni Relations')], max_length=1),
        ),
    ]
