# Generated by Django 3.1 on 2020-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200823_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('3', 'Unassigned'), ('2', 'Scholarship'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('1', 'Public Relations'), ('3', 'Social'), ('2', 'Health and Safety'), ('4', 'Unassigned'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('1', 'Public Relations'), ('5', 'Membership Development'), ('4', 'Alumni Relations'), ('3', 'Social'), ('2', 'Health and Safety'), ('6', 'Scholarship'), ('0', 'Recruitment')], max_length=1),
        ),
    ]
