# Generated by Django 3.0.7 on 2020-09-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200906_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('1', 'Membership Development'), ('2', 'Scholarship'), ('3', 'Unassigned'), ('0', 'Alumni Relations')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('3', 'Social'), ('0', 'Recruitment'), ('4', 'Unassigned'), ('1', 'Public Relations')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('4', 'Alumni Relations'), ('2', 'Health and Safety'), ('5', 'Membership Development'), ('3', 'Social'), ('0', 'Recruitment'), ('6', 'Scholarship'), ('1', 'Public Relations')], max_length=1),
        ),
    ]
