# Generated by Django 3.1 on 2020-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200823_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('0', 'Alumni Relations'), ('3', 'Unassigned'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('3', 'Social'), ('1', 'Public Relations'), ('0', 'Recruitment'), ('4', 'Unassigned')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('6', 'Scholarship'), ('2', 'Health and Safety'), ('3', 'Social'), ('5', 'Membership Development'), ('4', 'Alumni Relations'), ('1', 'Public Relations'), ('0', 'Recruitment')], max_length=1),
        ),
    ]
