# Generated by Django 3.0.7 on 2020-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200823_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('1', 'Membership Development'), ('3', 'Unassigned'), ('0', 'Alumni Relations'), ('2', 'Scholarship')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('0', 'Recruitment'), ('3', 'Social'), ('1', 'Public Relations'), ('4', 'Unassigned')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('0', 'Recruitment'), ('3', 'Social'), ('4', 'Alumni Relations'), ('6', 'Scholarship'), ('1', 'Public Relations'), ('5', 'Membership Development')], max_length=1),
        ),
    ]
