# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 15:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160619_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='cumulative_gpa',
            field=models.CharField(default=b'4.0', max_length=4),
        ),
        migrations.AddField(
            model_name='brother',
            name='past_semester_gpa',
            field=models.CharField(default=b'4.0', max_length=4),
        ),
        migrations.AddField(
            model_name='brother',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='brother',
            name='scholarship_plan',
            field=models.TextField(default=b'Scholarship plan has not been setup yet if you past semester GPA or cum GPA are below 3.0 you should setup a meeting to have this corrected'),
        ),
    ]
