# Generated by Django 3.0.7 on 2020-09-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200906_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemeetingevent',
            name='committee_chair',
        ),
        migrations.AddField(
            model_name='position',
            name='has_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('AR', 'Alumni Relations'), ('MD', 'Membership Development'), ('PH', 'Philanthropy'), ('SC', 'Scholarship'), ('NA', 'Unassigned')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('PR', 'Public Relations'), ('RE', 'Recruitment'), ('SO', 'Social'), ('HS', 'Health and Safety'), ('NA', 'Unassigned')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('AR', 'Alumni Relations'), ('MD', 'Membership Development'), ('PH', 'Philanthropy'), ('PR', 'Public Relations'), ('RE', 'Recruitment'), ('SC', 'Scholarship'), ('SO', 'Social'), ('HS', 'Health and Safety')], max_length=2, unique=True)),
                ('type', models.CharField(choices=[('S', 'Standing'), ('O', 'Operational')], max_length=1)),
                ('meeting_time', models.DurationField(blank=True, choices=[(1, 'Weekly'), (2, 'Biweekly'), (4, 'Monthly')])),
                ('chair', models.OneToOneField(limit_choices_to={'has_committee': True}, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Position')),
                ('members', models.ManyToManyField(blank=True, to='dashboard.Brother')),
            ],
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Committees'),
        ),
    ]
