# Generated by Django 3.0.7 on 2020-09-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200908_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committees',
            new_name='Committee',
        ),
    ]
