# Generated by Django 3.0.7 on 2020-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200823_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('0', 'Alumni Relations'), ('1', 'Membership Development'), ('3', 'Unassigned')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('4', 'Unassigned'), ('0', 'Recruitment'), ('1', 'Public Relations'), ('3', 'Social'), ('2', 'Health and Safety')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('0', 'Recruitment'), ('1', 'Public Relations'), ('3', 'Social'), ('4', 'Alumni Relations'), ('5', 'Membership Development'), ('2', 'Health and Safety'), ('6', 'Scholarship')], max_length=1),
        ),
    ]
