# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160619_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='email',
        ),
        migrations.AlterField(
            model_name='brother',
            name='cumulative_gpa',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='brother',
            name='past_semester_gpa',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
    ]
