# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160619_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Chapter Event', max_length=200)),
                ('date_time', models.DateTimeField()),
                ('mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventExcuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name=(b'I will not be attending %s because', None))),
                ('response_message', models.TextField(default=b'Your excuse was not approved because')),
                ('status', models.CharField(choices=[(b'0', b'Pending'), (b'1', b'Approved'), (b'2', b'Denied')], default=b'0', max_length=1)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Brother')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ChapterEvent')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Service Event', max_length=200)),
                ('description', models.TextField(default=b'I did the service thing')),
                ('hours', models.IntegerField(default=0)),
                ('submitted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Brother')),
            ],
        ),
    ]
