# Generated by Django 3.0.7 on 2020-09-09 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200908_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplies',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.AddField(
            model_name='committee',
            name='meeting_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='meeting_interval',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(days=7), 'Weekly'), (datetime.timedelta(days=14), 'Biweekly'), (datetime.timedelta(days=28), 'Monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='meeting_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00')]),
        ),
    ]
