# Generated by Django 3.1 on 2020-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200823_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('2', 'Scholarship'), ('3', 'Unassigned'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('3', 'Social'), ('4', 'Unassigned'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('3', 'Social'), ('5', 'Membership Development'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('0', 'Recruitment'), ('6', 'Scholarship'), ('4', 'Alumni Relations')], max_length=1),
        ),
    ]
