# Generated by Django 3.0.7 on 2020-09-11 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200909_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='type',
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='committee',
            name='meeting_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')]),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='healthandsafetyevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='healthandsafetyevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='scholarshipevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='studytableevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='studytableevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
    ]
