# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_brother_roster_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='roster_number',
            field=models.IntegerField(default=1856),
        ),
    ]
