# Generated by Django 3.0.7 on 2020-09-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200910_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='operational_committee',
        ),
        migrations.RemoveField(
            model_name='brother',
            name='standing_committee',
        ),
        migrations.RemoveField(
            model_name='position',
            name='ec',
        ),
        migrations.RemoveField(
            model_name='position',
            name='has_committee',
        ),
        migrations.AlterField(
            model_name='committee',
            name='chair',
            field=models.OneToOneField(limit_choices_to=models.Q(('title', 'Vice President of Health and Safety'), ('title', 'Recruitment Chair'), ('title', 'Scholarship Chair'), ('title', 'Philanthropy Chair'), ('title', 'Public Relations Chair'), ('title', 'Alumni Relations Chair'), ('title', 'Membership Development Chair'), ('title', 'Social Chair'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='dashboard.Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Vice President of Health and Safety', 'Vphs'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Marshal', 'Marshal'), ('Recruitment Chair', 'Recruitment Chair'), ('Scholarship Chair', 'Scholarship Chair'), ('Detail Manager', 'Detail Manager'), ('Philanthropy Chair', 'Philanthropy Chair'), ('Public Relations Chair', 'Public Relations Chair'), ('Service Chair', 'Service Chair'), ('Alumni Relations Chair', 'Alumni Relations Chair'), ('Membership Development Chair', 'Membership Development Chair'), ('Social Chair', 'Social Chair'), ('Adviser', 'Adviser')], max_length=45, unique=True),
        ),
    ]
