# Generated by Django 3.0.7 on 2020-08-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200823_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramLatest',
        ),
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('1', 'Membership Development'), ('2', 'Scholarship'), ('3', 'Unassigned')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('3', 'Social'), ('4', 'Unassigned'), ('0', 'Recruitment'), ('1', 'Public Relations'), ('2', 'Health and Safety')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('3', 'Social'), ('4', 'Alumni Relations'), ('0', 'Recruitment'), ('6', 'Scholarship'), ('5', 'Membership Development'), ('1', 'Public Relations'), ('2', 'Health and Safety')], max_length=1),
        ),
    ]
