# Generated by Django 3.0.7 on 2020-08-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200823_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('2', 'Scholarship'), ('3', 'Unassigned'), ('1', 'Membership Development')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('1', 'Public Relations'), ('0', 'Recruitment'), ('4', 'Unassigned'), ('3', 'Social'), ('2', 'Health and Safety')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('5', 'Membership Development'), ('1', 'Public Relations'), ('0', 'Recruitment'), ('4', 'Alumni Relations'), ('6', 'Scholarship'), ('3', 'Social'), ('2', 'Health and Safety')], max_length=1),
        ),
    ]
