# Generated by Django 3.0.7 on 2020-09-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200911_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('icon', models.ImageField(upload_to='media_icons')),
            ],
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='dashboard.Committee'),
        ),
        migrations.AlterField(
            model_name='position',
            name='brothers',
            field=models.ManyToManyField(to='dashboard.Brother'),
        ),
        migrations.CreateModel(
            name='MediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_accounts', to='dashboard.Brother')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.OnlineMedia')),
            ],
        ),
    ]
