# Generated by Django 3.0.7 on 2020-09-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200912_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('she/her/hers', 'Feminine'), ('he/him/his', 'Masculine'), ('they/them/theirs', 'Nonbinary')], max_length=30),
        ),
        migrations.AddField(
            model_name='brother',
            name='semester_graduating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brother_graduating', to='dashboard.Semester'),
        ),
    ]
