# Generated by Django 3.0.7 on 2020-08-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200824_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('1', 'Membership Development'), ('0', 'Alumni Relations'), ('2', 'Scholarship'), ('3', 'Unassigned')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('4', 'Unassigned'), ('1', 'Public Relations'), ('3', 'Social'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('5', 'Membership Development'), ('2', 'Health and Safety'), ('4', 'Alumni Relations'), ('1', 'Public Relations'), ('3', 'Social'), ('0', 'Recruitment'), ('6', 'Scholarship')], max_length=1),
        ),
    ]
