# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160619_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterevent',
            name='attendees',
            field=models.ManyToManyField(to='dashboard.Brother'),
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='event_type',
            field=models.CharField(choices=[(b'0', b'Chapter'), (b'1', b'Service'), (b'2', b'Philanthropy')], default=0, max_length=1),
        ),
    ]
