# Generated by Django 3.0.7 on 2020-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200827_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('0', 'Alumni Relations'), ('2', 'Scholarship'), ('1', 'Membership Development'), ('3', 'Unassigned')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('3', 'Social'), ('0', 'Recruitment'), ('1', 'Public Relations'), ('4', 'Unassigned')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('2', 'Health and Safety'), ('3', 'Social'), ('4', 'Alumni Relations'), ('0', 'Recruitment'), ('1', 'Public Relations'), ('5', 'Membership Development'), ('6', 'Scholarship')], max_length=1),
        ),
    ]
