# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20160621_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2016),
        ),
    ]
