# Generated by Django 3.0.7 on 2020-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200827_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('3', 'Unassigned'), ('1', 'Membership Development'), ('2', 'Scholarship'), ('0', 'Alumni Relations')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('4', 'Unassigned'), ('3', 'Social'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('6', 'Scholarship'), ('5', 'Membership Development'), ('3', 'Social'), ('4', 'Alumni Relations'), ('2', 'Health and Safety'), ('1', 'Public Relations'), ('0', 'Recruitment')], max_length=1),
        ),
    ]
