# Generated by Django 3.0.7 on 2020-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200827_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[('2', 'Scholarship'), ('1', 'Membership Development'), ('3', 'Unassigned'), ('0', 'Alumni Relations')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[('1', 'Public Relations'), ('3', 'Social'), ('4', 'Unassigned'), ('2', 'Health and Safety'), ('0', 'Recruitment')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[('1', 'Public Relations'), ('4', 'Alumni Relations'), ('3', 'Social'), ('2', 'Health and Safety'), ('0', 'Recruitment'), ('6', 'Scholarship'), ('5', 'Membership Development')], max_length=1),
        ),
    ]
