# Generated by Django 3.0.7 on 2020-09-13 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200827_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('icon', models.ImageField(upload_to='media_icons')),
            ],
        ),
        migrations.AlterModelOptions(
            name='supplies',
            options={'verbose_name_plural': 'Supplies'},
        ),
        migrations.RemoveField(
            model_name='brother',
            name='operational_committee',
        ),
        migrations.RemoveField(
            model_name='brother',
            name='standing_committee',
        ),
        migrations.RemoveField(
            model_name='position',
            name='ec',
        ),
        migrations.AddField(
            model_name='brother',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('FEM', 'she/her/hers'), ('MASC', 'he/him/his'), ('NON', 'they/them/theirs')], max_length=30),
        ),
        migrations.AddField(
            model_name='brother',
            name='semester_graduating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brother_graduating', to='dashboard.Semester'),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='healthandsafetyevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='healthandsafetyevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='position',
            name='brothers',
            field=models.ManyToManyField(to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Vice President of Health and Safety', 'Vice President Of Health And Safety'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Marshal', 'Marshal'), ('Recruitment Chair', 'Recruitment Chair'), ('Scholarship Chair', 'Scholarship Chair'), ('Detail Manager', 'Detail Manager'), ('Philanthropy Chair', 'Philanthropy Chair'), ('Public Relations Chair', 'Public Relations Chair'), ('Service Chair', 'Service Chair'), ('Alumni Relations Chair', 'Alumni Relations Chair'), ('Membership Development Chair', 'Membership Development Chair'), ('Social Chair', 'Social Chair'), ('Adviser', 'Adviser')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='scholarshipevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='studytableevent',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], null=True),
        ),
        migrations.AlterField(
            model_name='studytableevent',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')], default=datetime.time(0, 0)),
        ),
        migrations.CreateModel(
            name='MediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_accounts', to='dashboard.Brother')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.OnlineMedia')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('AR', 'Alumni Relations'), ('MD', 'Membership Development'), ('PH', 'Philanthropy'), ('PR', 'Public Relations'), ('RE', 'Recruitment'), ('SC', 'Scholarship'), ('SO', 'Social'), ('HS', 'Health and Safety')], max_length=2, unique=True)),
                ('meeting_interval', models.IntegerField(blank=True, choices=[(7, 'Weekly'), (14, 'Biweekly'), (28, 'Monthly')], null=True)),
                ('meeting_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('meeting_time', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 A.M.'), (datetime.time(9, 30), '9:30 A.M.'), (datetime.time(10, 0), '10:00 A.M.'), (datetime.time(10, 30), '10:30 A.M.'), (datetime.time(11, 0), '11:00 A.M.'), (datetime.time(11, 30), '11:30 A.M.'), (datetime.time(12, 0), '12:00 P.M.'), (datetime.time(12, 30), '12:30 P.M.'), (datetime.time(13, 0), '1:00 P.M.'), (datetime.time(13, 30), '1:30 P.M.'), (datetime.time(14, 0), '2:00 P.M.'), (datetime.time(14, 30), '2:30 P.M.'), (datetime.time(15, 0), '3:00 P.M.'), (datetime.time(15, 30), '3:30 P.M.'), (datetime.time(16, 0), '4:00 P.M.'), (datetime.time(16, 30), '4:30 P.M.'), (datetime.time(17, 0), '5:00 P.M.'), (datetime.time(17, 30), '5:30 P.M.'), (datetime.time(18, 0), '6:00 P.M.'), (datetime.time(18, 30), '6:30 P.M.'), (datetime.time(19, 0), '7:00 P.M.'), (datetime.time(19, 30), '7:30 P.M.'), (datetime.time(20, 0), '8:00 P.M.'), (datetime.time(20, 30), '8:30 P.M.')])),
                ('chair', models.OneToOneField(limit_choices_to=models.Q(('title', 'Vice President of Health and Safety'), ('title', 'Recruitment Chair'), ('title', 'Scholarship Chair'), ('title', 'Philanthropy Chair'), ('title', 'Public Relations Chair'), ('title', 'Alumni Relations Chair'), ('title', 'Membership Development Chair'), ('title', 'Social Chair'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='dashboard.Position')),
                ('members', models.ManyToManyField(blank=True, to='dashboard.Brother')),
            ],
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='dashboard.Committee'),
        ),
    ]
