# Generated by Django 3.0.7 on 2020-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200913_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('brothers', models.ManyToManyField(related_name='classes', to='dashboard.Brother')),
            ],
        ),
        migrations.CreateModel(
            name='CampusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('brothers', models.ManyToManyField(related_name='groups', to='dashboard.Brother')),
            ],
        ),
    ]
