# Generated by Django 3.0.7 on 2020-09-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200913_2012'),
        ('dashboard', '0016_auto_20200913_1752'),
    ]

    operations = [
    ]
