# Generated by Django 3.0.7 on 2020-09-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200913_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_tree_brother', to='dashboard.Brother')),
                ('notified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phone_tree_notified_by', to='dashboard.Brother')),
            ],
        ),
    ]
