# Generated by Django 3.0.7 on 2020-10-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_campusgroup_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='name',
        ),
        migrations.AddField(
            model_name='classes',
            name='department',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brother',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('FEM', 'she/her/hers'), ('MASC', 'he/him/his'), ('NON', 'they/them/theirs')], max_length=4),
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee',
            field=models.CharField(choices=[('AR', 'Alumni Relations'), ('MD', 'Membership Development'), ('PH', 'Philanthropy'), ('PR', 'Public Relations'), ('RE', 'Recruitment'), ('SC', 'Scholarship'), ('SO', 'Social'), ('HS', 'Health And Safety')], max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='dashboard.Brother')),
                ('class_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Classes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('class_taken', 'brother'), name='unique_class'),
        ),
    ]
