# Generated by Django 3.0.7 on 2020-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20201003_0223'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_class',
        ),
        migrations.AddConstraint(
            model_name='classes',
            constraint=models.CheckConstraint(check=models.Q(('number__gte', 101), ('number__lte', 600)), name='number_constraint'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('class_taken', 'brother'), name='unique_grade'),
        ),
    ]
