# Generated by Django 3.0.7 on 2020-10-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20201003_2359'),
        ('dashboard', '0018_auto_20200920_2225'),
    ]

    operations = [
    ]
