# Generated by Django 3.0.7 on 2020-10-07 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_merge_20201006_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusgroup',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='MeetABrother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('week', models.DateField(default=django.utils.timezone.now)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_brother', to='dashboard.Brother')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_candidate', to='dashboard.Brother')),
            ],
        ),
    ]
