# Generated by Django 3.0.7 on 2020-10-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20201006_2306'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meetabrother',
            constraint=models.UniqueConstraint(fields=('brother', 'candidate'), name='unique_meet_a_brother'),
        ),
    ]
