# Generated by Django 3.0.7 on 2020-10-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20201007_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetabrother',
            name='brother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brother_mab', to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='meetabrother',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mab', to='dashboard.Brother'),
        ),
    ]
