# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_scholarshipreport_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuse',
            name='status',
            field=models.CharField(choices=[(b'0', b'Pending'), (b'1', b'Approved'), (b'2', b'Denied'), (b'3', b'Non-Mandatory')], default=b'0', max_length=1),
        ),
    ]
