# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20160622_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excuse',
            name='semester',
        ),
    ]
