# Generated by Django 3.0.7 on 2020-11-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20201011_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Vice President of Health and Safety', 'Vice President of Health and Safety'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Marshal', 'Marshal'), ('Recruitment Chair', 'Recruitment Chair'), ('Scholarship Chair', 'Scholarship Chair'), ('Detail Manager', 'Detail Manager'), ('Philanthropy Chair', 'Philanthropy Chair'), ('Public Relations Chair', 'Public Relations Chair'), ('Service Chair', 'Service Chair'), ('Alumni Relations Chair', 'Alumni Relations Chair'), ('Membership Development Chair', 'Membership Development Chair'), ('Social Chair', 'Social Chair'), ('Community Standards Chair', 'Community Standards Chair'), ('OX Roast Chair', 'OX Roast Chair'), ('Damage Chair', 'Damage Chair'), ('Greek Games Chair', 'Greek Games Chair'), ('Historian', 'Historian'), ('First Guard', 'First Guard'), ('Second Guard', 'Second Guard'), ('Internal Change Chair', 'Internal Change Chair'), ('Standards Board Justice', 'Standards Board Justice'), ('Executive Council Member At Large', 'Executive Council Member At Large'), ('House Manager', 'House Manager'), ('Risk Manager', 'Risk Manager'), ('IFC Rep', 'IFC Rep'), ('Awards Chair', 'Awards Chair'), ('Food Steward', 'Food Steward'), ('Athletics Chair', 'Athletics Chair'), ('Dashboard Chair', 'Dashboard Chair'), ('Adviser', 'Adviser')], max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_officer', models.BooleanField(default=True)),
                ('information', models.TextField()),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.Brother')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.Position')),
            ],
        ),
    ]
