# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_excuse_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='rsvp_brothers',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='dashboard.PotentialNewMember'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='rsvp_brothers',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='studytableevent',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
    ]
