# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-23 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20160622_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuse',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicesubmission',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='response_message',
            field=models.TextField(default=b'Please fill out if excuse was not approved'),
        ),
    ]
