# Generated by Django 3.0.7 on 2020-11-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_meetabrother_urmom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetabrother',
            name='urmom',
        ),
    ]
