# Generated by Django 3.0.7 on 2020-11-14 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_meetabrother_urmom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='dashboard.Brother')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='dashboard.Position')),
            ],
        ),
    ]
