# Generated by Django 3.0.7 on 2020-11-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_officer',
            field=models.BooleanField(default=True),
        ),
    ]
