# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-23 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20160623_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytableevent',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
