# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-23 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20160623_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='chapterevent',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='philanthropyevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='philanthropyevent',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='recruitmentevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='recruitmentevent',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='studytableevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='studytableevent',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
