# Generated by Django 3.0.7 on 2020-11-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20201114_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='dashboard.Position'),
        ),
    ]
