# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-24 03:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20160623_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='emergency_contact',
            field=models.CharField(default=b'Chapter President', max_length=200),
        ),
        migrations.AddField(
            model_name='brother',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='brother',
            name='major',
            field=models.CharField(default=b'Undecided', max_length=200),
        ),
        migrations.AddField(
            model_name='brother',
            name='minor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='t_shirt_size',
            field=models.CharField(default=b'M', max_length=5),
        ),
    ]
