# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20160630_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialnewmember',
            name='email',
        ),
        migrations.AddField(
            model_name='potentialnewmember',
            name='case_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
