# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-07 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20160630_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubmission',
            name='submitted',
        ),
        migrations.AddField(
            model_name='servicesubmission',
            name='status',
            field=models.CharField(choices=[(b'0', b'Pending'), (b'1', b'Awaiting Approval'), (b'2', b'Approved'), (b'3', b'Denied')], default=b'0', max_length=1),
        ),
    ]
