# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_studytableevent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipreport',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
