# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-23 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_scholarshipreport_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ec',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
