# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20160729_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='date_pledged',
            field=models.DateField(blank=True, null=True),
        ),
    ]
