# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_brother_date_pledged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemeetingevent',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='brother',
            name='roster_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
