# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20160811_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemeetingevent',
            name='minutes',
            field=models.URLField(blank=True, null=True),
        ),
    ]
