# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_committeemeetingevent_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=256)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
