# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
