# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_supplies_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='when',
            field=models.DateField(auto_now_add=True),
        ),
    ]
