# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20160914_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Event', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('minutes', models.URLField(blank=True, null=True)),
                ('attendees_brothers', models.ManyToManyField(blank=True, to='dashboard.Brother')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Semester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='chapterevent',
            old_name='attendees',
            new_name='attendees_brothers',
        ),
        migrations.RenameField(
            model_name='committeemeetingevent',
            old_name='attendees',
            new_name='attendees_brothers',
        ),
        migrations.RenameField(
            model_name='studytableevent',
            old_name='attendees',
            new_name='attendees_brothers',
        ),
        migrations.RemoveField(
            model_name='committeemeetingevent',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='attendees',
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeemeetingevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='attendees_brothers',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
        migrations.AddField(
            model_name='philanthropyevent',
            name='minutes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='minutes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='attendees_brothers',
            field=models.ManyToManyField(blank=True, to='dashboard.Brother'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='minutes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='minutes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytableevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='philanthropyevent',
            name='rsvp_brothers',
            field=models.ManyToManyField(blank=True, related_name='rsvp_philanthropy', to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='name',
            field=models.CharField(default=b'Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='rsvp_brothers',
            field=models.ManyToManyField(blank=True, related_name='rsvp_service', to='dashboard.Brother'),
        ),
    ]
