# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20160914_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='house_detail_buyout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brother',
            name='in_house',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='kitchen_detail_buyout',
            field=models.BooleanField(default=False),
        ),
    ]
