# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20161214_1859'),
        ('dashboard', '0053_auto_20161214_1910'),
    ]

    operations = [
    ]
