# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAndSafteyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Event', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('minutes', models.URLField(blank=True, null=True)),
                ('attendees_brothers', models.ManyToManyField(blank=True, to='dashboard.Brother')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
