# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_healthandsafteyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='brothers',
            field=models.ManyToManyField(related_name='brothers', to='dashboard.Brother'),
        ),
        migrations.AlterField(
            model_name='position',
            name='brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brother', to='dashboard.Brother'),
        ),
    ]
