# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-21 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_healthandsafetyevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brother',
            old_name='house_detail_buyout',
            new_name='does_house_details',
        ),
        migrations.RenameField(
            model_name='brother',
            old_name='kitchen_detail_buyout',
            new_name='does_kitchen_details',
        ),
    ]
