# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-25 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20161221_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brothers', models.ManyToManyField(to='dashboard.Brother')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='SundayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=64)),
                ('long_description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SundayGroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ManyToManyField(to='dashboard.SundayDetail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DetailGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ThursdayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=64)),
                ('long_description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Brother')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
