# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 04:37
from __future__ import unicode_literals

from django.db import migrations


def make_position_many_brothers(apps, schema_editor):
    Position = apps.get_model('dashboard', 'Position')

    for pos in Position.objects.all():
        if pos.brother:
            pos.brothers.add(pos.brother)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20161226_0428'),
    ]

    operations = [
        migrations.RunPython(make_position_many_brothers),
    ]
