# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20161226_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='brother',
        ),
    ]
