# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-26 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_detailgroup_sundaydetail_sundaygroupdetail_thursdaydetail'),
        ('dashboard', '0058_remove_position_brother'),
    ]

    operations = [
    ]
