# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-31 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20161231_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundaydetail',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Brother'),
        ),
    ]
