# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_sundaydetail_finished_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundaygroupdetail',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 8, 5, 34, 51, 356292, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brother',
            name='operational_committee',
            field=models.CharField(choices=[(b'2', b'Scholarship'), (b'1', b'Membership Development'), (b'0', b'Alumni Relations'), (b'3', b'Unassigned')], default=b'3', max_length=1),
        ),
        migrations.AlterField(
            model_name='brother',
            name='standing_committee',
            field=models.CharField(choices=[(b'2', b'Health and Safety'), (b'3', b'Social'), (b'1', b'Public Relations'), (b'0', b'Recruitment'), (b'4', b'Unassigned')], default=b'4', max_length=1),
        ),
        migrations.AlterField(
            model_name='committeemeetingevent',
            name='committee',
            field=models.CharField(choices=[(b'3', b'Social'), (b'6', b'Scholarship'), (b'4', b'Alumni Relations'), (b'2', b'Health and Safety'), (b'1', b'Public Relations'), (b'5', b'Membership Development'), (b'0', b'Recruitment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2017),
        ),
    ]
