# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20200721_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=b'media/photos'),
        ),
    ]
