# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20200721_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=b'photos'),
        ),
    ]
