# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-27 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20200721_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=b'minecraft')),
            ],
        ),
    ]
