# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-03 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_minecraftphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_shortcode', models.CharField(max_length=255)),
            ],
        ),
    ]
