# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_instagramlatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentevent',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentevent',
            name='picture',
            field=models.ImageField(default=12, upload_to=b'recruitment'),
            preserve_default=False,
        ),
    ]
