# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20200816_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='committeemeetingevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='healthandsafetyevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='philanthropyevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recruitmentevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='scholarshipevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='serviceevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studytableevent',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='recruitmentevent',
            name='picture',
            field=models.ImageField(null=True, upload_to=b'recruitment'),
        ),
    ]
